#!/bin/bash
# Firebase Setup Script for ClawChat
# Run this script after creating your Firebase project

echo "🔔 ClawChat Firebase Setup"
echo "=============================="
echo ""
echo "Prerequisites:"
echo "1. Create a project at https://console.firebase.google.com/"
echo "2. Add iOS app with bundle ID: com.openclaw.clawchat"
echo "3. Download GoogleService-Info.plist"
echo "4. Enable Firebase Cloud Messaging"
echo ""
echo "Steps:"
echo "--------"
echo "1. Place your GoogleService-Info.plist in: ios/Runner/"
echo "2. Enable Push Notifications in Xcode:"
echo "   - Open ios/Runner.xcworkspace"
echo "   - Select Runner > Signing & Capabilities"
echo "   - Add 'Push Notifications' capability"
echo "   - Add 'Background Modes' capability"
echo "     - Check 'Remote notifications'"
echo "     - Check 'Background fetch'"
echo ""
echo "3. (Optional) APNs Setup:"
echo "   - Create APNs Auth Key or Certificate in Apple Developer Portal"
echo "   - Upload to Firebase Console > Project Settings > Cloud Messaging"
echo ""
echo "4. Run: flutter pub get"
echo ""
echo "Note: For development, you can use Firebase Local Emulator Suite"
